site_name: Mango Framework Documentation
site_url: https://example.com
repo_url: https://github.com/MarkoGasta/Mango-Framework
repo_name: Mango-Framework

theme:
  name: material
  palette: 
    scheme: slate
    primary: orange
    accent: yellow
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/mango_color.png
  favicon: assets/mango_color.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.code.copy
    - toc.follow

nav:
  - Home: 
    - Welcome: index.md
    - Features: home/features.md

  - Install:
    - From Source: install/from_source.md
    - From Place: install/from_place.md
  - Usage:
    - Top-Level Layout: usage/layout.md
    - Creating a Service: usage/creating_service.md
    - Creating a Controller: usage/creating_controller.md
    - Managing Priorities: usage/set_priorities.md
    - Connecting Modules: usage/connecting_modules.md
    - Language Server: usage/language_server.md
  - Docs:
    - Internal:
      - ReplicatedStorage:
        - Controllers: docs/internal/ReplicatedStorage/controllers.md
        - Resources: docs/internal/ReplicatedStorage/resources.md
        - Settings: docs/internal/ReplicatedStorage/settings.md
        - MangoClient: docs/internal/ReplicatedStorage/mango_client.md
        - MangoControllers: docs/internal/ReplicatedStorage/mango_controllers.md
        - MangoResources: docs/internal/ReplicatedStorage/mango_resources.md
      - ServerStorage:
        - Services: docs/internal/ServerStorage/services.md
        - Resources: docs/internal/ServerStorage/resources.md
        - MangoServer: docs/internal/ServerStorage/mango_server.md
        - MangoServices: docs/internal/ServerStorage/mango_services.md
        - MangoResources: docs/internal/ServerStorage/mango_resources.md
    - Branches:
      - Main: docs/branches/main.md
      - Barebones: docs/branches/barebones.md
      - Dev: docs/branches/dev.md
        
  - About:  
    - Faq: about/faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format