site_name: Mango Framework Documentation
site_url: https://example.com
theme:
  name: material
  palette: 
    scheme: slate
    primary: orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/mango_color.png
  favicon: assets/mango_color.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences